application:
  name: service-utilisateur  # Nom de l'application pour identification dans Eureka

spring:
  cloud:
    config:
      uri: http://localhost:8888  # Adresse de votre Config Server
      import: "optional:configserver:"  # Utilisation correcte de configserver avec optional pour éviter l'erreur
      import-check:
        enabled: false  # Désactiver la vérification de l'importation de configuration

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/  # Adresse de votre Eureka Server

  management:
    tracing:
      sampling:
        probability: 1.0  # Taux d'échantillonnage pour la traçabilité (1.0 signifie que toutes les requêtes seront tracées)
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans  # URL du serveur Zipkin pour collecter et visualiser les traces

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exposer tous les endpoints d'administration
  prometheus:
    metrics:
      export:
        enabled: true
ribbon:
  eureka:
    enabled: false
  listOfServers: localhost:8807,localhost:8808
